name: Auto-Generate Documentation (Node.js)
on:
  push:
    paths:
      - 'Examples.Core/**/*.cs'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'Examples.Core/**/*.cs'
    types: [opened, synchronize]

env:
  LITELLM_API_KEY: ${{ secrets.LITELLM_API_KEY }}
  GITHUB_GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
  DOCUMENTATION_REPO: ${{ secrets.DOCUMENTATION_REPO }}
  DOCUMENTATION_TOKEN: ${{ secrets.DOCUMENTATION_REPO_TOKEN }}

jobs:
  detect-new-examples:
    runs-on: ubuntu-latest
    outputs:
      examples: ${{ steps.detect.outputs.examples }}
      has_new_examples: ${{ steps.detect.outputs.has_new_examples }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '.github/scripts/package.json'

      - name: Install Dependencies
        working-directory: .github/scripts
        run: npm ci

      - name: Detect New Examples
        id: detect
        working-directory: .github/scripts
        run: node detect-examples.js

  create-gists:
    needs: detect-new-examples
    if: needs.detect-new-examples.outputs.has_new_examples == 'true'
    runs-on: ubuntu-latest
    outputs:
      gist_data: ${{ steps.create_gists.outputs.gist_data }}
    strategy:
      matrix:
        example: ${{ fromJson(needs.detect-new-examples.outputs.examples) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '.github/scripts/package.json'

      - name: Install Dependencies
        working-directory: .github/scripts
        run: npm ci

      - name: Create GitHub Gists
        id: create_gists
        working-directory: .github/scripts
        run: |
          node create-gists.js \
            --example-file "${{ matrix.example }}" \
            --examples-repo ".."

  generate-documentation:
    needs: [detect-new-examples, create-gists]
    if: needs.detect-new-examples.outputs.has_new_examples == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: ${{ fromJson(needs.detect-new-examples.outputs.examples) }}
    steps:
      - name: Checkout Examples Repo
        uses: actions/checkout@v4
        with:
          path: examples-repo

      - name: Checkout Documentation Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.DOCUMENTATION_REPO }}
          token: ${{ env.DOCUMENTATION_TOKEN }}
          path: docs-repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'examples-repo/.github/scripts/package.json'

      - name: Install Dependencies
        working-directory: examples-repo/.github/scripts
        run: npm ci

      - name: Generate Documentation
        working-directory: examples-repo/.github/scripts
        run: |
          node generate-docs.js \
            --example-file "${{ matrix.example }}" \
            --examples-repo "../.." \
            --docs-repo "../../../docs-repo"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          path: docs-repo
          token: ${{ env.DOCUMENTATION_TOKEN }}
          commit-message: 'docs: Add documentation for ${{ matrix.example }}'
          title: 'Auto-generated documentation for ${{ matrix.example }}'
          body: |
            ## Auto-generated Documentation

            This PR was automatically generated for the new example: `${{ matrix.example }}`

            ### Changes
            - Added documentation based on code analysis using AI
            - Created interactive GitHub Gist with complete example code
            - Followed existing documentation structure and patterns
            - Included code examples, Gist embeds, and proper formatting

            ### Source
            Generated from: `${{ matrix.example }}`
            Repository: `${{ github.repository }}`
            Commit: `${{ github.sha }}`

            Please review the generated content for accuracy and completeness.

            ---
            *Generated by Node.js auto-documentation system*
          branch: auto-docs/${{ matrix.example }}-${{ github.run_number }}
          delete-branch: true
